apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: pocv
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: pocv
  filterTags:
    pattern: "^pocv-v(.*)$"
    extract: "$1"
  policy:
    semver:
      range: ">=0.0.0-0"
