apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - customer-management/
  - party-management/
  - product-catalog-management/
  - qualification/
  - shopping-cart/
  - pocv/
