apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: bff
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bff
  filterTags:
    pattern: "^demo-ui-v(.*)-bff$"
    extract: "$1"
  policy:
    semver:
      range: ">=0.0.0-0"
