apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tmf-platform
  namespace: tmf
  annotations:
    cert-manager.io/cluster-issuer: tmf-selfsigned-issuer
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tmf.home.arpa
      secretName: tmf-platform-tls
  rules:
    - host: tmf.home.arpa
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: tmf-platform-bff
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tmf-platform-demo-ui
                port:
                  number: 80
