apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tmf-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: raino@rohekood.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tmf-platform-tls
  namespace: tmf
spec:
  secretName: tmf-platform-tls
  dnsNames:
    - tmf.home.arpa
  issuerRef:
    name: tmf-selfsigned-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tmf-rohekood-tls
  namespace: tmf
spec:
  secretName: tmf-rohekood-tls
  dnsNames:
    - tmf.rohekood.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
