apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tmf-platform
  namespace: tmf
spec:
  interval: 5m
  chart:
    spec:
      chart: ./releases/charts/tmf-platform
      sourceRef:
        kind: GitRepository
        name: tmf-ai-demo
        namespace: flux-system
  values:
    bff:
      enabled: true
      image:
        tag: demo-ui-v0.5.2-bff # {"$imagepolicy": "flux-system:bff:tag"}
      env:
        secretName: tmf-secrets
        auth0Domain: ""
        auth0Audience: ""
    customer-management:
      enabled: true
      image:
        tag: customer-management-v0.1.1 # {"$imagepolicy": "flux-system:customer-management:tag"}
      env:
        secretName: tmf-secrets
    demo-ui:
      enabled: true
      image:
        tag: demo-ui-v0.5.2-ui # {"$imagepolicy": "flux-system:demo-ui:tag"}
      service:
        type: ClusterIP
        port: 80
      env:
        secretName: tmf-secrets
        auth0DomainKey: AUTH0_DOMAIN
        auth0ClientIdKey: AUTH0_CLIENT_ID
        auth0AudienceKey: AUTH0_AUDIENCE
        apiUrl: ""
        apiBaseUrl: ""
    emissary:
      enabled: false
      # Optional: set hostname (DNS/IP) to require Host header matching.
      hostname: ""
      createHost: false
      mapping:
        apiPrefix: /api/
        uiPrefix: /
    party-management:
      enabled: true
      image:
        tag: party-management-v0.1.0 # {"$imagepolicy": "flux-system:party-management:tag"}
      env:
        secretName: tmf-secrets
    pocv:
      enabled: true
      image:
        tag: pocv-v0.1.0 # {"$imagepolicy": "flux-system:pocv:tag"}
      env:
        secretName: tmf-secrets
    product-catalog-management:
      enabled: true
      image:
        tag: product-catalog-management-v0.1.0 # {"$imagepolicy": "flux-system:product-catalog-management:tag"}
      env:
        secretName: tmf-secrets
    qualification:
      enabled: true
      image:
        tag: qualification-v0.2.0 # {"$imagepolicy": "flux-system:qualification:tag"}
      env:
        secretName: tmf-secrets
        redisAddr: redis-master.tmf.svc.cluster.local:6379
    shopping-cart:
      enabled: true
      image:
        tag: shopping-cart-v0.2.0 # {"$imagepolicy": "flux-system:shopping-cart:tag"}
      env:
        secretName: tmf-secrets
