apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tmf-gitops
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/rohekood/tmf-gitops
  ref:
    branch: main
  secretRef:
    name: enercon-release-auth
