apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: shopping-cart
  namespace: flux-system
spec:
  interval: 1m
  image: ghcr.io/rohekood/shopping-cart
  secretRef:
    name: github-registry
