apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: party-management
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: party-management
  filterTags:
    pattern: "^party-management-v(.*)$"
    extract: "$1"
  policy:
    semver:
      range: ">=0.0.0-0"
