---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: tmf-party
  namespace: tmf
spec:
  name: tmf.party
  type: topic
  durable: true
  autoDelete: false
  vhost: tmf
  rabbitmqClusterReference:
    connectionSecret:
      name: rabbitmq-topology-credentials
